# https://v2.nuxt.com/deployments/github-pages/#github-actions
name: github-pages-deploy

# define the trigger
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    env:
      # We used "docs" as directory name for our documentation, we will be referencing this later
      working-directory: .

    strategy:
      matrix:
        os: [ubuntu-latest]
        # https://pnpm.io/installation#compatibility
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # Downloads, configures and caches Node.js
      - name: Setup node env
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      # Install all dependencies needed to build our documentation
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: pnpm install

      # The generate command is used to invoke Nuxt static site generation
      - name: Generate
        working-directory: ${{env.working-directory}}
        # https://nuxt.com/deploy/github-pages
        # 未使用自定义域名时, 须配置 NUXT_APP_BASE_URL 环境变量值
        # 同 https://<user>.github.io/<repository>/ 中的 /<repository>/
        run: NUXT_APP_BASE_URL=/gobang-vue/ pnpm build --preset github_pages

      # Pushes the files to a branch called "gh-pages" that will be used as deployment branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # This token is automatically invoked
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Nuxt export the statically generated files in the dist directory by default
          publish_dir: ./.output/public
